### ISSUE TITLE
AttributeError: module 'torch.utils._pytree' has no attribute 'register_pytree_node'

### ISSUE THREAD

**Issue by weny911** [CASIA-IVA-Lab/FiLo#1]
![image](https://github.com/user-attachments/assets/c3242135-d3c2-4ae2-b458-ced51c0650f4)

Among them, I downloaded `4` weights and put them in the `ckpt` folder, and the dataset path of the `.sh` file has also been modified, and then the `torch` version follows require, and after I searched, someone has a problem with master `transformes`, what do you think?

**Comment by weny911** [comment]
Thank you for your excellent work, I would like to ask you a question, which is as follows

**Comment by wliu23** [comment]
Hello, I have the same problem. Have you solved it yet？

**Comment by liwenyang-911** [comment]
> Hello, I have the same problem. Have you solved it yet？

no, I suggest that torch version problem.

**Comment by weny911** [comment]
> e you solved it yet？

I solved it.

**Comment by weny911** [comment]
okay
