### ISSUE TITLE
How can I use my own dataset

### ISSUE THREAD

**Issue by wliu23** [CASIA-IVA-Lab/FiLo#3]
Hi author, when I try to use my own dataset for training, I need to supplement the "anomaly_detail_gpt" information, and how to get this information seems to be missing in your paper. Could you please provide a template for asking questions to gpt?
![image](https://github.com/user-attachments/assets/000fb903-398d-42da-9f1d-0e608c2ec870)

**Comment by FantasticGNU** [comment]
Thanks for your attention! You can directly use GPT to generate the corresponding potential anomaly category, using "Based on your knowledge, what anomalies might occur on [class name]?"
