### ISSUE TITLE
Qeustion about the batch size & patch_tokens

### ISSUE THREAD

**Issue by sonstory** [CASIA-IVA-Lab/FiLo#5]
First, thank you for doing great research and sharing it.

Looking at the code, the batch size is set to 1 as default value, so if the shape of the patch tokens is (Batch_size(=1), 4(intermediate layer), 1369, 1024) in the code below, is it correct that no convolution operation via `ConvLayer()` is performed and all operations are performed on the `LinearLayer()`?

```
patch_tokens_qkv = self.decoder_linear(patch_tokens[::2])
patch_tokens_vv = self.decoder_cov(patch_tokens[1::2])
```

**Comment by FantasticGNU** [comment]
No, the first dimension of patch_tokens is 8, which represents features extracted from different intermediate layers. You can print the shape of patch_tokens to view it.
